import type { ConnectorDefinition, ConnectorProvider } from "./types";

export const connectorRegistry: ConnectorDefinition[] = [
  {
    provider: "x",
    label: "X",
    shortLabel: "X",
    description: "Near-real-time public buyer-intent discovery from matching posts.",
    health: "available",
    capabilities: ["public_discovery", "search", "webhooks", "reply"],
    priority: 1,
    credentialEnv: ["X_BEARER_TOKEN"],
    note: "Best first source for broad public intent discovery.",
  },
  {
    provider: "instagram",
    label: "Instagram",
    shortLabel: "IG",
    description: "Professional-account comments, mentions, messages and permitted media activity.",
    health: "available",
    capabilities: ["comments", "mentions", "messages", "webhooks", "reply"],
    priority: 2,
    credentialEnv: ["META_APP_ID", "META_APP_SECRET"],
    note: "Best for activity around a connected business account, not unrestricted personal-account search.",
  },
  {
    provider: "facebook",
    label: "Facebook",
    shortLabel: "FB",
    description: "Facebook Page activity and Messenger conversations for connected businesses.",
    health: "available",
    capabilities: ["messages", "page_activity", "comments", "webhooks", "reply"],
    priority: 3,
    credentialEnv: ["META_APP_ID", "META_APP_SECRET"],
    note: "Private-group scraping is not part of the product architecture.",
  },
  {
    provider: "threads",
    label: "Threads",
    shortLabel: "TH",
    description: "Public Threads discovery and connected-account activity where supported.",
    health: "available",
    capabilities: ["public_discovery", "mentions", "search", "reply"],
    priority: 4,
    credentialEnv: ["META_APP_ID", "META_APP_SECRET"],
    note: "Shares Meta infrastructure but uses its own API surface and permissions.",
  },
  {
    provider: "youtube",
    label: "YouTube",
    shortLabel: "YT",
    description: "Keyword discovery and buyer-intent analysis across videos and comments.",
    health: "available",
    capabilities: ["search", "comments"],
    priority: 5,
    credentialEnv: ["YOUTUBE_API_KEY"],
    note: "Useful for recommendation and service-request language in comments.",
  },
  {
    provider: "reddit",
    label: "Reddit",
    shortLabel: "RD",
    description: "Community recommendation and purchase-intent discovery.",
    health: "approval_required",
    capabilities: ["public_discovery", "search", "comments"],
    priority: 6,
    credentialEnv: ["REDDIT_CLIENT_ID", "REDDIT_CLIENT_SECRET"],
    note: "Commercial access should only be enabled after the required Reddit approval/agreement.",
  },
  {
    provider: "nextdoor",
    label: "Nextdoor",
    shortLabel: "ND",
    description: "Hyperlocal neighborhood demand and business activity.",
    health: "approval_required",
    capabilities: ["page_activity", "webhooks"],
    priority: 7,
    credentialEnv: ["NEXTDOOR_CLIENT_ID", "NEXTDOOR_CLIENT_SECRET"],
    note: "Partner/API approval is required before production access.",
  },
  {
    provider: "tiktok",
    label: "TikTok",
    shortLabel: "TT",
    description: "Authorized creator/business activity with limited broad buyer-intent discovery.",
    health: "limited",
    capabilities: ["page_activity", "webhooks"],
    priority: 8,
    credentialEnv: ["TIKTOK_CLIENT_KEY", "TIKTOK_CLIENT_SECRET"],
    note: "Useful as an account connector; not treated as a universal public-post firehose.",
  },
  {
    provider: "linkedin",
    label: "LinkedIn",
    shortLabel: "LI",
    description: "B2B company activity, comments and lead signals for approved applications.",
    health: "limited",
    capabilities: ["page_activity", "comments", "mentions"],
    priority: 9,
    credentialEnv: ["LINKEDIN_CLIENT_ID", "LINKEDIN_CLIENT_SECRET"],
    note: "Most valuable for B2B verticals rather than residential local services.",
  },
];

export function getConnector(provider: ConnectorProvider) {
  return connectorRegistry.find((item) => item.provider === provider);
}
